apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: ks-prometheus-demo
  name: ks-prometheus-demo
  namespace: kubesphere-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30861
  selector:
    app: kubesphere
    component: ks-prometheus-demo
    tier: backend
  sessionAffinity: None
  type: NodePort